# Generated by Django 4.2.18 on 2025-01-31 10:52

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(default=api.models.generateUID, max_length=50, unique=True)),
                ('name', models.CharField(max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('number', models.CharField(max_length=13, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('file', models.FileField(upload_to=api.models.get_upload_path)),
                ('created_at', models.DateField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
