# Generated by Django 4.2.18 on 2025-01-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='name',
            field=models.CharField(default='defaultname', max_length=200),
            preserve_default=False,
        ),
    ]
