# Generated by Django 4.2.18 on 2025-02-03 22:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_mfa_enabled_user_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedownloadlink',
            name='permission',
            field=models.IntegerField(choices=[(1, 'Read'), (2, 'Write')], default=api.models.PermissionTypes['Read']),
        ),
    ]
