# Generated by Django 4.2.18 on 2025-02-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_filedownloadlink_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='key',
            field=models.CharField(blank=True, max_length=44, null=True),
        ),
    ]
