# Generated by Django 4.2.18 on 2025-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_files_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='key',
        ),
        migrations.AddField(
            model_name='files',
            name='iv',
            field=models.BinaryField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='salt',
            field=models.BinaryField(blank=True, max_length=16, null=True),
        ),
    ]
