# Generated by Django 4.2.18 on 2025-02-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_files_key_files_iv_files_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='iv',
        ),
        migrations.RemoveField(
            model_name='files',
            name='salt',
        ),
        migrations.AddField(
            model_name='files',
            name='key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
