# Generated by Django 4.2.18 on 2025-02-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_files_iv_remove_files_salt_files_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
