# Generated by Django 4.2.18 on 2025-02-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_files_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='key',
        ),
        migrations.AddField(
            model_name='files',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
