

services:
  backend:
    build: ./backend
    container_name: fileshare-backend
    networks:
      - fileshare_network
    volumes:
      - ./certs:/app/certs
    ports:
      - "8443:8443"

  frontend:
    build: ./frontend
    container_name: fileshare-frontend
    networks:
      - fileshare_network
    volumes:
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"

networks:
  fileshare_network:
    driver: bridge
